name: Build Default
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Display PATH environment
        run: echo $PATH
        
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /var/www/stuntsync-user
            git pull
            export NODE_OPTIONS="--max-old-space-size=8192"
            /home/imaginecup/.nvm/versions/node/v20.11.0/bin/yarn install
            /home/imaginecup/.nvm/versions/node/v20.11.0/bin/yarn build
            cp ../htaccess ./build/.htaccess
            sudo systemctl restart apache2
