name: Build Default
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Update $PATH
        run: echo "::add-path::/home/imaginecup/.yarn/bin:/home/imaginecup/bin:/usr/local/bin:/home/imaginecup/.yarn/bin:/home/imaginecup/.nvm/versions/node/v20.11.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

      - name: Display PATH environment
        run: echo $PATH
        
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /var/www/stuntsync-user
            git pull
            export NODE_OPTIONS="--max-old-space-size=8192"
            yarn install
            yarn build
            cp ../htaccess ./build/.htaccess
            sudo systemctl restart apache2
